[commands.setup]
property.unknown = "Setting could not be found."
property.get = "<aqua><property> <reset> == <value>"
property.set = "<pri><property> <reset>= <value>"
property.allset = "Alle Einstellungen = <value>"
property.list.single = "<gray><property><reset> = <hover:show_text:'Change to <notvalue> '><click:run_command:'/setup property %b %b'><value></click></hover>"
property.list = "<green><bold>Properties<reset>:<newline><properties>"

lobby.set = "Lobby world was set."
boundary.set = "Boundary has been set."
spawn.set = "Spawn point has been set."
end = "Config has been saved."

help = "<red><bold>SETUP: <reset><newline>1. <click:run_command:'/setup lobby'>Lobby-Welt setzen</click><newline>2. <click:suggest_command:'/setup boundary 30'>Boundary setzen (Minimum Y Höhe)</click><newline>3. <click:run_command:'/setup spawnpoint'>Spawn setzen</click><newline>4. <click:run_command:'/setup queueNPC'>Queue NPC setzen</click><newline>4. <click:run_command:'/setup properties'>Properties bearbeiten</click><newline>5. <click:run_command:'/setup end'>Setup fertigstellen</click>"

[hotbar]
challenge = "<gray>Challenge"
clan = "<yellow>Clan"
items = "<gold>Items"
friends = "<green>Friends"
language = "<red>Language"
lobby = "<aqua>Lobby"

nick.nicked = "<gray>You are <dark_gray>: <green>nicked"
nick.unnicked = "<gray>You are<dark_gray>: <red>not nicked"
nicked.development = "In development"

[kitsorting]
saved = "The inventory sorting has been saved."
error = "An error occurred. Please try again or contact support."
reset = "Reset"

[scoreboard]
clan = """
  <br>Clan<gray>:
  <br><gray><clan>
  <br>
  <br>Clan Elo<gray>:
  <br><gray><clanelo>
  <br>
  <br>Clan Level<gray>:
  <br><gray><clanlevel>★
  <br>
  <br>Clan Coins<gray>:
  <br><gold><clancoins>
  <br>
  <br>Clan Spieler<gray>:
  <br><aqua><onlineclanmembers><gray>/<dark_gray><totalclanmembers>
"""

self = """
  <br>Rank<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Playtime<gray>:
  <br><yellow><hours>h
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Friends<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""

selfSecondary = """
  <br>Rang<gray>:
  <br><rank>
  <br>
  <br>Elo<gray>:
  <br><gray><elo>
  <br>
  <br>Level<gray>:
  <br><level>
  <br>
  <br>Coins<gray>:
  <br><gold><coins>
  <br>
  <br>Friends<gray>:
  <br><green><onlinefriends><gray>/<dark_gray><totalfriends>
"""
